# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch pickmylight
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm ci
      - name: Build PWA
        run: npm run build -- --configuration=production
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist/pizza-app
    #steps:
    #- uses: actions/checkout@v1
    #- name: Use Node.js 12.18.3
    #  uses: actions/setup-node@v1
    #  with:
    #    node-version: 12.18.3
    #- name: Build and Deploy
    #  uses: JamesIves/github-pages-deploy-action@releases/v2
    #  env:
    #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #    BASE_BRANCH: master
    #    BRANCH: gh-pages
    #    FOLDER: dist/pizza-app
    #    BUILD_SCRIPT: npm install && npm run build -- --prod
